name: Rust Service Build and Release

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'  # 递归检出submodules
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        default: true
    - name: Install protobuf-compiler
      run: sudo apt-get update && sudo apt-get install -y protobuf-compiler
    - name: Build Release in Service
      working-directory: ./service
      run: cargo build --release
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: testmode
        release_name: Release testmode
        draft: false
        prerelease: false
    - name: Print current directory
      run: pwd
    - name: List files in the current directory
      run: ls -lah ./target
    - name: move to service name
      run: cp ./target/release/post-service ./target/release/service
    - name: Zip the build
      run: zip -j ./target/release/service.zip ./target/release/service
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./target/release/service.zip
        asset_name: service.zip
        asset_content_type: application/zip
